### ISSUE TITLE
"Could not detect a WaveformData adapter from the input"

### ISSUE THREAD

**Issue by samstarling** [bbcrd/peaks.js#106]
Hello,

I'm getting the following error in my Javascript console when using a `.dat` file as the `dataUri` for Peaks.js:

    Could not detect a WaveformData adapter from the input.

I'm generating the file like this:

    audiowaveform -i 20141218-180000-greg-james.mp3 -o 20141218-180000-greg-james.dat

Generating a `.json` file in the same way works fine, although the waveform appears to be constantly clipped (see screenshot below), even though the MP3 is not. Any ideas what I'm doing wrong? Thanks!

![screen shot 2014-12-22 at 16 11 16](https://cloud.githubusercontent.com/assets/42478/5527347/3672aeca-89f5-11e4-9233-50ee6ce7e1b4.png)

**Comment by oncletom** [comment]
We had a chat yesterday with @chrisn about this issue. A reasonable breakdown of the improvements could be:

- more explicit end to end documentation, from an audio file to a Web-based waveform;
- 16 bits data reader
- to switch `audiowaveform` to 8 bits by default – but it is a breaking change and we are conscious about the relevancy of such a decision

Let us know if you have other feedbacks, I suppose we can consider this issue as closed :-)

**Comment by samstarling** [comment]
That sounds good to me @oncletom - improving the documentation would help, particularly an end-to-end example like that. And yes, the breaking change could be dealt with just as easily by adding a note about using it in the 8 bit mode. Thanks!
