### ISSUE TITLE
Zoom causes a browser freeze if done after waveformOverviewReady

### ISSUE THREAD

**Issue by ziggythehamster** [bbcrd/peaks.js#114]
Tested browsers:
* Safari 7.1.3 (OS X Mavericks)
* Safari 7.1.4 (OS X Mavericks)
* Firefox 38 (OS X Mavericks)
* Opera Developer 30.0.1820.0 (OS X Mavericks)
* IE 11 (Windows 8.1)
* IE 11 (Windows 10)

I haven't tried it with Project Spartan, but I have no reason to believe that it will work there.

If I have the following init code (where peaks is `window.peaks` because Browserify doesn't work as expected with ES6 modules and I don't want to figure out why):

```coffeescript
    $mediaElement = $("audio")
    p = peaks.init
      container: $(".waveform-container").get(0)
      height: 200
      logger: console.error.bind(console)
      mediaElement: $mediaElement.get(0)
      segments: []
      zoomLevels: [256, 512, 2048, 8192]

      dataUri:
        arraybuffer: "https://SOME_BUCKET.s3.amazonaws.com/SOME_FILE.dat"

    p.zoom.setZoom(2)
```

Then zoom works as expected: I am now zoomed at the 2048 zoom level.

If I zoom after `waveformOverviewReady` fires, the browser locks up. If I don't zoom like I'm doing here, it still locks up. The demo that is currently in master under `npm run start` freezes as well. I was able to get a LITTLE bit of profiling information from IE (and only IE) and it seems like it's freezing in `Kinetic.Animation._animate`. All I see is a bunch of garbage collection for tens of seconds (and then I stopped the profiler). Maybe it's stuck in an infinite loop?

I think this is also why the build is failing to run properly under CI - perhaps it times out because the browser freezes.

What should I try to diagnose this? Is there something I can configure or comment out to make it zoom without animating?

**Comment by lowpitch** [comment]
ello,

I've also experienced this locking-up, and the cause seems to be a bug in the version of the Kinetic node module that's pulled in.

If you're building your own version of peaks.js, a temporary workaround is to make a change in the kinetic.js file to fix the bug, then to rebuild. For me, around line #10184 there's a function called getIntersection - this is where the infinite loop occurs. There's a block of code which looks like:

```javascript
// if no shape, and no antialiased pixel, we should end searching
 if (continueSearch) {
  spiralSearchDistance += 1;
} else {
  return;
}
```

Change this to

```javascript
// if no shape, and no antialiased pixel, we should end searching
 if (continueSearch) {
  continueSearch = false;
  spiralSearchDistance += 1;
} else {
  return;
}
```

and the loop will no longer run forever.

I am currently working on a more performant zoom animation that does not rely on Kinetic which should be available soon, but I hope this helps you in the mean time.

**Comment by ziggythehamster** [comment]
This does, and I am building my own, so I will make this change. I wonder if this is something that's fixed in KonvaJS, and if Peaks will work without too many changes with KonvaJS (the fork of KineticJS that is still maintained).

**Comment by ziggythehamster** [comment]
The actual problem was a lack of checking in `WaveformZoomView` - `seekFrame` would get passed a `pixelIndex` which was NaN, then attempt to do something in the canvas with NaN. If you add a check there, you'll see that the animation is doing the wrong thing, and can easily fix that bug.

Of course, the problem appears to be happening in KineticJS is where the NaN is a problem...so it looks like a KineticJS problem! So, I ended up switching to using Konva.js and fixing the bug in PR #118 :).

Enjoy! :)
