### ISSUE TITLE
Waveform displayed does not match PNG output from audiowaveform

### ISSUE THREAD

**Issue by ziggythehamster** [bbcrd/peaks.js#115]
My peaks.js instance does not render my .dat or .json outputs properly. Audiowaveform does, and it looks right.

Here's the output from audiowaveform:

![audiowaveform](https://cloud.githubusercontent.com/assets/66674/6991716/3752231a-da5a-11e4-91d2-23e14f58af2b.png)

Same file loaded into Peaks (tested in Safari and Opera Developer):

![peaks](https://cloud.githubusercontent.com/assets/66674/6991721/5f6d0d24-da5a-11e4-9fbb-e511a43a8547.png)

If you want to give this a shot yourself, [here is my test .dat file](https://art19-development.s3-us-west-1.amazonaws.com/inagaddadavida.dat). Supply your own audio or figure out what you need to change in the URL to make it give you a MP3. The .json output is even worse, because it's pretty much just a solid green area with occasional drops.

Tested with latest master.

**Comment by chrisn** [comment]
Hi Keith,

At present, Peaks.js only correctly works with 8-bit waveform data, so you should use the `-b 8` option when running audiowaveform. By default, audiowaveform outputs 16-bit binary data, which isn't currently supported by Peaks.js. This is something we should document, as you're not the first to be caught by this issue (see [#106](https://github.com/bbcrd/peaks.js/issues/106)).

At some point we'll update the project to add handling of 16-bit data, but for now I recommend generating and using 8-bit data.

Chris

**Comment by ziggythehamster** [comment]
Ah, awesome! I thought that maybe I was losing my mind or something since I was using the default output from audiowaveform. Thanks! :)

**Comment by ziggythehamster** [comment]
Closing due to resolution in 6ed4f83

**Comment by oncletom** [comment]
:+1:
