### ISSUE TITLE
GPL hurts diffusion of innovation

### ISSUE THREAD

**Issue by JohnTigue** [bbcrd/peaks.js#148]
This is good software, produced by a good organization. Thank you for the effort.

Nonetheless, for browser-based JavaScript licensing under GPL (in any of its flavors) may well hinder the adoption of the innovation. JavaScript devs look for MIT/BSD/Apache style licensing. 

Clearly this is an opinionated statement upon a topic that quickly leads into heated discussions. But simply licensing liberally means the discussion does not happen and so diffusion of innovation is improved. There are other functionally equivalent projects which can be used without having to drop into the GPL licensing discussion rabbit hole.

**Comment by chrisn** [comment]
Peaks.js uses code from an existing GPL licensed project, and with their permission we are able to license Peaks.js as LGPL. We have to be respectful of the original authors' wishes.

**Comment by JohnTigue** [comment]
Ah, understood. Thanks for the quick response.

**Comment by jdelStrother** [comment]
@chrisn do you recall what the GPL'd code is?
