### ISSUE TITLE
Waveform scrolling continues after mouseup

### ISSUE THREAD

**Issue by chrisn** [bbcrd/peaks.js#149]
Dragging to scroll the waveform in the zoom view can result in the waveform continuing to scroll when the mouse is moved, after the user has released the mouse button. The problem occurs in Chrome and Firefox on Ubuntu (possibly also other browsers and OSs).

To see the problem, open the Peaks.js Demo Page (index.html).

1. Click on the zoom view and hold the mouse button down
2. Move the cursor outside the zoom view
3. Release the mouse button
4. Move the cursor within the zoom view
5. Notice that the zoom view still scrolls even though the mouse button has been released

This problem is caused (in `waveform.zoomview.js`, and likely also in `waveform.overview.js`) when the user releases the mouse button outside the view container, as the view never receives the `mouseup` event.

**Comment by chrisn** [comment]
The same behaviour occurs if the user switches between browser tabs or applications (Ctrl/Alt-Tab) while the mouse button is held down.

**Comment by jdelStrother** [comment]
I have a potential fix for this in a branch I've not PR'd yet.   What do you think to https://github.com/jdelStrother/peaks.js/commit/491a3530a2784472911720b2c3b06e569e958c64 ?

**Comment by chrisn** [comment]
I'll give it a test, thanks!

**Comment by chrisn** [comment]
This works nicely, but the problem with Ctrl/Alt-Tab remains.

**Comment by jdelStrother** [comment]
I guess adding an event listener for window.onblur would fix that.   Want
me to tidy it up & submit a PR?

**Comment by chrisn** [comment]
Sorry for the delay. Yes, please do send a PR.
